
import { Machine } from './types';

export const MACHINES_DATA: Machine[] = [
  {
    id: '1',
    name: 'Linde H25D',
    model: 'H25 - Serie 1202',
    brand: 'Linde',
    year: 2022,
    hours: 1500,
    weight: 2.5,
    type: 'both',
    category: 'Carrelli Diesel',
    price: 28500,
    rentalPrice: '80€ / giorno',
    condition: 'NUOVO',
    imageUrl: 'https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?q=80&w=2070&auto=format&fit=crop',
    features: ['Trasmissione Idrostatica', 'Cabina Ergonomica', 'Doppio Pedale'],
    description: 'Carrello elevatore diesel Linde ad alte prestazioni, affidabile e preciso per ogni tipo di carico.'
  },
  {
    id: '2',
    name: 'Cesab B200',
    model: 'B215-218-220',
    brand: 'Cesab',
    year: 2023,
    hours: 200,
    weight: 2.0,
    type: 'both',
    category: 'Carrelli Elettrici',
    price: 32000,
    rentalPrice: '95€ / giorno',
    condition: 'USATO',
    imageUrl: 'https://images.unsplash.com/photo-1621259182978-f09e5e2ca09a?q=80&w=2072&auto=format&fit=crop',
    features: ['Motore AC', 'Batteria al Litio', 'Dimensioni Compatte'],
    description: 'Innovazione elettrica Cesab per magazzini che richiedono agilità e sostenibilità.'
  },
  {
    id: '3',
    name: 'Merlo TF35.7',
    model: 'Turbofarmer',
    brand: 'Merlo',
    year: 2021,
    hours: 2500,
    weight: 3.5,
    type: 'both',
    category: 'Piattaforme Aeree',
    price: 65000,
    rentalPrice: '150€ / giorno',
    condition: 'OTTIME CONDIZIONI',
    imageUrl: 'https://images.unsplash.com/photo-1579412690850-bd41cd0ca397?q=80&w=2070&auto=format&fit=crop',
    features: ['Sbraccio 7m', 'Cabina FOPS/ROPS', 'Gancio Traino'],
    description: 'Sollevatore telescopico Merlo perfetto per edilizia e agricoltura.'
  },
  {
    id: '4',
    name: 'Hitachi ZX19-6',
    model: 'Zaxis',
    brand: 'Hitachi',
    year: 2023,
    hours: 50,
    weight: 1.9,
    type: 'both',
    category: 'Mini Escavatori',
    price: 24500,
    rentalPrice: '120€ / giorno',
    condition: 'NUOVO',
    imageUrl: 'https://images.unsplash.com/photo-1517520287167-4bda64282b54?q=80&w=2070&auto=format&fit=crop',
    features: ['Sottocarro Allargabile', 'Braccio Lungo', 'Cingoli in Gomma'],
    description: 'Mini escavatore versatile per lavori di precisione in spazi ristretti.'
  },
  {
    id: '5',
    name: 'Linde E16 EVO',
    model: 'E16-02',
    brand: 'Linde',
    year: 2024,
    weight: 1.6,
    type: 'rental',
    category: 'Carrelli Elettrici',
    rentalPrice: '110€ / giorno',
    condition: 'NUOVO',
    imageUrl: 'https://images.unsplash.com/photo-1542385151-efd9000785a0?q=80&w=1978&auto=format&fit=crop',
    features: ['Inviluppo di Sterzo', 'Gestione Batteria Intelligente', 'Sicurezza Attiva'],
    description: 'Il top della gamma elettrica Linde, disponibile ora per il noleggio a breve e lungo termine.'
  },
  {
    id: '6',
    name: 'Cesab M300D',
    model: 'M320',
    brand: 'Cesab',
    year: 2022,
    hours: 1200,
    weight: 3.0,
    type: 'sale',
    category: 'Carrelli Diesel',
    price: 22000,
    condition: 'USATO',
    imageUrl: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?q=80&w=2070&auto=format&fit=crop',
    features: ['Motore Stage V', 'Montante Visibilità Totale', 'Sedile Ammortizzato'],
    description: 'Potenza e comfort Cesab in un carrello diesel robusto per carichi pesanti.'
  }
];
